# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26a87e670803416df2d2fb32138904c602612beb609f9016f33631762c924b0a2124088176f30bee18b501eb1d5d35862de4e4066cd61280e2a79dbaa55fb48

test:
  secret_key_base: f944d1009f9ad53922d044b533454967962648e0be4226ebe2d2a5181b154dae9025af7024de0cab61a02dc0165b4f44ed6c061aef8005b7e52d0544fd1ccd99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
